# batchcandlenums - batch candle nums
batchcandlenums: 30
# dbpath - db path
dbpath: ./
# dbengine - db engine
dbengine: leveldb
# bindaddr - grpc server bind address
bindaddr: 0.0.0.0:5002
# loglevel - log level
loglevel: debug
# db2markets - markets
db2markets:
  - jrj
  - bitmex
# tokens - tokens
tokens:
  - wzDkh9h2fhfUVuS9jZ8uVbhV3vC5AWX3