// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.22.0
// 	protoc        v3.11.2
// source: tradingdb2.proto

package tradingpb

import (
	context "context"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

// Candle - candle
type Candle struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ts              int64   `protobuf:"varint,1,opt,name=ts,proto3" json:"ts,omitempty"`
	Open            int64   `protobuf:"varint,2,opt,name=open,proto3" json:"open,omitempty"`
	Close           int64   `protobuf:"varint,3,opt,name=close,proto3" json:"close,omitempty"`
	High            int64   `protobuf:"varint,4,opt,name=high,proto3" json:"high,omitempty"`
	Low             int64   `protobuf:"varint,5,opt,name=low,proto3" json:"low,omitempty"`
	Volume          int64   `protobuf:"varint,6,opt,name=volume,proto3" json:"volume,omitempty"`
	OpenInterest    int64   `protobuf:"varint,7,opt,name=openInterest,proto3" json:"openInterest,omitempty"`
	Trades          int64   `protobuf:"varint,8,opt,name=trades,proto3" json:"trades,omitempty"`
	Vwap            float64 `protobuf:"fixed64,9,opt,name=vwap,proto3" json:"vwap,omitempty"`
	LastSize        int64   `protobuf:"varint,10,opt,name=lastSize,proto3" json:"lastSize,omitempty"`
	Turnover        int64   `protobuf:"varint,11,opt,name=turnover,proto3" json:"turnover,omitempty"`
	HomeNotional    float64 `protobuf:"fixed64,12,opt,name=homeNotional,proto3" json:"homeNotional,omitempty"`
	ForeignNotional float64 `protobuf:"fixed64,13,opt,name=foreignNotional,proto3" json:"foreignNotional,omitempty"`
}

func (x *Candle) Reset() {
	*x = Candle{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tradingdb2_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Candle) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Candle) ProtoMessage() {}

func (x *Candle) ProtoReflect() protoreflect.Message {
	mi := &file_tradingdb2_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Candle.ProtoReflect.Descriptor instead.
func (*Candle) Descriptor() ([]byte, []int) {
	return file_tradingdb2_proto_rawDescGZIP(), []int{0}
}

func (x *Candle) GetTs() int64 {
	if x != nil {
		return x.Ts
	}
	return 0
}

func (x *Candle) GetOpen() int64 {
	if x != nil {
		return x.Open
	}
	return 0
}

func (x *Candle) GetClose() int64 {
	if x != nil {
		return x.Close
	}
	return 0
}

func (x *Candle) GetHigh() int64 {
	if x != nil {
		return x.High
	}
	return 0
}

func (x *Candle) GetLow() int64 {
	if x != nil {
		return x.Low
	}
	return 0
}

func (x *Candle) GetVolume() int64 {
	if x != nil {
		return x.Volume
	}
	return 0
}

func (x *Candle) GetOpenInterest() int64 {
	if x != nil {
		return x.OpenInterest
	}
	return 0
}

func (x *Candle) GetTrades() int64 {
	if x != nil {
		return x.Trades
	}
	return 0
}

func (x *Candle) GetVwap() float64 {
	if x != nil {
		return x.Vwap
	}
	return 0
}

func (x *Candle) GetLastSize() int64 {
	if x != nil {
		return x.LastSize
	}
	return 0
}

func (x *Candle) GetTurnover() int64 {
	if x != nil {
		return x.Turnover
	}
	return 0
}

func (x *Candle) GetHomeNotional() float64 {
	if x != nil {
		return x.HomeNotional
	}
	return 0
}

func (x *Candle) GetForeignNotional() float64 {
	if x != nil {
		return x.ForeignNotional
	}
	return 0
}

// Candles - candles
type Candles struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Market  string    `protobuf:"bytes,1,opt,name=market,proto3" json:"market,omitempty"`
	Symbol  string    `protobuf:"bytes,2,opt,name=symbol,proto3" json:"symbol,omitempty"`
	Tag     string    `protobuf:"bytes,3,opt,name=tag,proto3" json:"tag,omitempty"`
	Candles []*Candle `protobuf:"bytes,4,rep,name=candles,proto3" json:"candles,omitempty"`
}

func (x *Candles) Reset() {
	*x = Candles{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tradingdb2_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Candles) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Candles) ProtoMessage() {}

func (x *Candles) ProtoReflect() protoreflect.Message {
	mi := &file_tradingdb2_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Candles.ProtoReflect.Descriptor instead.
func (*Candles) Descriptor() ([]byte, []int) {
	return file_tradingdb2_proto_rawDescGZIP(), []int{1}
}

func (x *Candles) GetMarket() string {
	if x != nil {
		return x.Market
	}
	return ""
}

func (x *Candles) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *Candles) GetTag() string {
	if x != nil {
		return x.Tag
	}
	return ""
}

func (x *Candles) GetCandles() []*Candle {
	if x != nil {
		return x.Candles
	}
	return nil
}

// FundSize - fund size
type FundSize struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Size float32 `protobuf:"fixed32,1,opt,name=size,proto3" json:"size,omitempty"`
	Time int64   `protobuf:"varint,2,opt,name=time,proto3" json:"time,omitempty"`
}

func (x *FundSize) Reset() {
	*x = FundSize{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tradingdb2_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FundSize) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FundSize) ProtoMessage() {}

func (x *FundSize) ProtoReflect() protoreflect.Message {
	mi := &file_tradingdb2_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FundSize.ProtoReflect.Descriptor instead.
func (*FundSize) Descriptor() ([]byte, []int) {
	return file_tradingdb2_proto_rawDescGZIP(), []int{2}
}

func (x *FundSize) GetSize() float32 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *FundSize) GetTime() int64 {
	if x != nil {
		return x.Time
	}
	return 0
}

// FundManager - fund manager
type FundManager struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name      string        `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	StartTime int64         `protobuf:"varint,2,opt,name=startTime,proto3" json:"startTime,omitempty"`
	EndTime   int64         `protobuf:"varint,3,opt,name=endTime,proto3" json:"endTime,omitempty"`
	BirthYear int64         `protobuf:"varint,4,opt,name=birthYear,proto3" json:"birthYear,omitempty"`
	Sex       bool          `protobuf:"varint,5,opt,name=sex,proto3" json:"sex,omitempty"`
	Education string        `protobuf:"bytes,6,opt,name=education,proto3" json:"education,omitempty"`
	Country   string        `protobuf:"bytes,7,opt,name=country,proto3" json:"country,omitempty"`
	Resume    string        `protobuf:"bytes,8,opt,name=resume,proto3" json:"resume,omitempty"`
	Results   []*FundResult `protobuf:"bytes,9,rep,name=results,proto3" json:"results,omitempty"`
}

func (x *FundManager) Reset() {
	*x = FundManager{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tradingdb2_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FundManager) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FundManager) ProtoMessage() {}

func (x *FundManager) ProtoReflect() protoreflect.Message {
	mi := &file_tradingdb2_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FundManager.ProtoReflect.Descriptor instead.
func (*FundManager) Descriptor() ([]byte, []int) {
	return file_tradingdb2_proto_rawDescGZIP(), []int{3}
}

func (x *FundManager) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *FundManager) GetStartTime() int64 {
	if x != nil {
		return x.StartTime
	}
	return 0
}

func (x *FundManager) GetEndTime() int64 {
	if x != nil {
		return x.EndTime
	}
	return 0
}

func (x *FundManager) GetBirthYear() int64 {
	if x != nil {
		return x.BirthYear
	}
	return 0
}

func (x *FundManager) GetSex() bool {
	if x != nil {
		return x.Sex
	}
	return false
}

func (x *FundManager) GetEducation() string {
	if x != nil {
		return x.Education
	}
	return ""
}

func (x *FundManager) GetCountry() string {
	if x != nil {
		return x.Country
	}
	return ""
}

func (x *FundManager) GetResume() string {
	if x != nil {
		return x.Resume
	}
	return ""
}

func (x *FundManager) GetResults() []*FundResult {
	if x != nil {
		return x.Results
	}
	return nil
}

type FundResult struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MaxDrawdown          float32 `protobuf:"fixed32,1,opt,name=maxDrawdown,proto3" json:"maxDrawdown,omitempty"`
	Sharpe               float32 `protobuf:"fixed32,2,opt,name=sharpe,proto3" json:"sharpe,omitempty"`
	AnnualizedReturns    float32 `protobuf:"fixed32,3,opt,name=annualizedReturns,proto3" json:"annualizedReturns,omitempty"`
	AnnualizedVolatility float32 `protobuf:"fixed32,4,opt,name=annualizedVolatility,proto3" json:"annualizedVolatility,omitempty"`
	TotalReturns         float32 `protobuf:"fixed32,5,opt,name=totalReturns,proto3" json:"totalReturns,omitempty"`
	StartTime            int64   `protobuf:"varint,6,opt,name=startTime,proto3" json:"startTime,omitempty"`
	EndTime              int64   `protobuf:"varint,7,opt,name=endTime,proto3" json:"endTime,omitempty"`
	Name                 string  `protobuf:"bytes,8,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *FundResult) Reset() {
	*x = FundResult{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tradingdb2_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FundResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FundResult) ProtoMessage() {}

func (x *FundResult) ProtoReflect() protoreflect.Message {
	mi := &file_tradingdb2_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FundResult.ProtoReflect.Descriptor instead.
func (*FundResult) Descriptor() ([]byte, []int) {
	return file_tradingdb2_proto_rawDescGZIP(), []int{4}
}

func (x *FundResult) GetMaxDrawdown() float32 {
	if x != nil {
		return x.MaxDrawdown
	}
	return 0
}

func (x *FundResult) GetSharpe() float32 {
	if x != nil {
		return x.Sharpe
	}
	return 0
}

func (x *FundResult) GetAnnualizedReturns() float32 {
	if x != nil {
		return x.AnnualizedReturns
	}
	return 0
}

func (x *FundResult) GetAnnualizedVolatility() float32 {
	if x != nil {
		return x.AnnualizedVolatility
	}
	return 0
}

func (x *FundResult) GetTotalReturns() float32 {
	if x != nil {
		return x.TotalReturns
	}
	return 0
}

func (x *FundResult) GetStartTime() int64 {
	if x != nil {
		return x.StartTime
	}
	return 0
}

func (x *FundResult) GetEndTime() int64 {
	if x != nil {
		return x.EndTime
	}
	return 0
}

func (x *FundResult) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

// Fund - fund
type Fund struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code       string         `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Name       string         `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Tags       []string       `protobuf:"bytes,3,rep,name=tags,proto3" json:"tags,omitempty"`
	CreateTime int64          `protobuf:"varint,4,opt,name=createTime,proto3" json:"createTime,omitempty"`
	Size       []*FundSize    `protobuf:"bytes,5,rep,name=size,proto3" json:"size,omitempty"`
	Company    string         `protobuf:"bytes,6,opt,name=company,proto3" json:"company,omitempty"`
	Managers   []*FundManager `protobuf:"bytes,7,rep,name=managers,proto3" json:"managers,omitempty"`
	Results    []*FundResult  `protobuf:"bytes,8,rep,name=results,proto3" json:"results,omitempty"`
}

func (x *Fund) Reset() {
	*x = Fund{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tradingdb2_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Fund) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Fund) ProtoMessage() {}

func (x *Fund) ProtoReflect() protoreflect.Message {
	mi := &file_tradingdb2_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Fund.ProtoReflect.Descriptor instead.
func (*Fund) Descriptor() ([]byte, []int) {
	return file_tradingdb2_proto_rawDescGZIP(), []int{5}
}

func (x *Fund) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *Fund) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Fund) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *Fund) GetCreateTime() int64 {
	if x != nil {
		return x.CreateTime
	}
	return 0
}

func (x *Fund) GetSize() []*FundSize {
	if x != nil {
		return x.Size
	}
	return nil
}

func (x *Fund) GetCompany() string {
	if x != nil {
		return x.Company
	}
	return ""
}

func (x *Fund) GetManagers() []*FundManager {
	if x != nil {
		return x.Managers
	}
	return nil
}

func (x *Fund) GetResults() []*FundResult {
	if x != nil {
		return x.Results
	}
	return nil
}

// SymbolInfo - symbol infomation
type SymbolInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Market string `protobuf:"bytes,1,opt,name=market,proto3" json:"market,omitempty"`
	Symbol string `protobuf:"bytes,2,opt,name=symbol,proto3" json:"symbol,omitempty"`
	Fund   *Fund  `protobuf:"bytes,3,opt,name=fund,proto3" json:"fund,omitempty"`
}

func (x *SymbolInfo) Reset() {
	*x = SymbolInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tradingdb2_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SymbolInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SymbolInfo) ProtoMessage() {}

func (x *SymbolInfo) ProtoReflect() protoreflect.Message {
	mi := &file_tradingdb2_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SymbolInfo.ProtoReflect.Descriptor instead.
func (*SymbolInfo) Descriptor() ([]byte, []int) {
	return file_tradingdb2_proto_rawDescGZIP(), []int{6}
}

func (x *SymbolInfo) GetMarket() string {
	if x != nil {
		return x.Market
	}
	return ""
}

func (x *SymbolInfo) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *SymbolInfo) GetFund() *Fund {
	if x != nil {
		return x.Fund
	}
	return nil
}

// RequestUpdCandles - request UpdCandles
type RequestUpdCandles struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Deprecated: Do not use.
	Token        string            `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	Candles      *Candles          `protobuf:"bytes,2,opt,name=candles,proto3" json:"candles,omitempty"`
	BasicRequest *BasicRequestData `protobuf:"bytes,3,opt,name=basicRequest,proto3" json:"basicRequest,omitempty"`
}

func (x *RequestUpdCandles) Reset() {
	*x = RequestUpdCandles{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tradingdb2_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RequestUpdCandles) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestUpdCandles) ProtoMessage() {}

func (x *RequestUpdCandles) ProtoReflect() protoreflect.Message {
	mi := &file_tradingdb2_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestUpdCandles.ProtoReflect.Descriptor instead.
func (*RequestUpdCandles) Descriptor() ([]byte, []int) {
	return file_tradingdb2_proto_rawDescGZIP(), []int{7}
}

// Deprecated: Do not use.
func (x *RequestUpdCandles) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *RequestUpdCandles) GetCandles() *Candles {
	if x != nil {
		return x.Candles
	}
	return nil
}

func (x *RequestUpdCandles) GetBasicRequest() *BasicRequestData {
	if x != nil {
		return x.BasicRequest
	}
	return nil
}

// ReplyUpdCandles - reply UpdCandles
type ReplyUpdCandles struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	LengthOK int32 `protobuf:"varint,1,opt,name=lengthOK,proto3" json:"lengthOK,omitempty"`
}

func (x *ReplyUpdCandles) Reset() {
	*x = ReplyUpdCandles{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tradingdb2_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReplyUpdCandles) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReplyUpdCandles) ProtoMessage() {}

func (x *ReplyUpdCandles) ProtoReflect() protoreflect.Message {
	mi := &file_tradingdb2_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReplyUpdCandles.ProtoReflect.Descriptor instead.
func (*ReplyUpdCandles) Descriptor() ([]byte, []int) {
	return file_tradingdb2_proto_rawDescGZIP(), []int{8}
}

func (x *ReplyUpdCandles) GetLengthOK() int32 {
	if x != nil {
		return x.LengthOK
	}
	return 0
}

// RequestGetCandles - request GetCandles
type RequestGetCandles struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Deprecated: Do not use.
	Token  string `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	Market string `protobuf:"bytes,2,opt,name=market,proto3" json:"market,omitempty"`
	Symbol string `protobuf:"bytes,3,opt,name=symbol,proto3" json:"symbol,omitempty"`
	// Deprecated: Do not use.
	Tag          string            `protobuf:"bytes,4,opt,name=tag,proto3" json:"tag,omitempty"`
	TsStart      int64             `protobuf:"varint,5,opt,name=tsStart,proto3" json:"tsStart,omitempty"`
	TsEnd        int64             `protobuf:"varint,6,opt,name=tsEnd,proto3" json:"tsEnd,omitempty"`
	Tags         []string          `protobuf:"bytes,7,rep,name=tags,proto3" json:"tags,omitempty"`
	BasicRequest *BasicRequestData `protobuf:"bytes,8,opt,name=basicRequest,proto3" json:"basicRequest,omitempty"`
}

func (x *RequestGetCandles) Reset() {
	*x = RequestGetCandles{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tradingdb2_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RequestGetCandles) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestGetCandles) ProtoMessage() {}

func (x *RequestGetCandles) ProtoReflect() protoreflect.Message {
	mi := &file_tradingdb2_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestGetCandles.ProtoReflect.Descriptor instead.
func (*RequestGetCandles) Descriptor() ([]byte, []int) {
	return file_tradingdb2_proto_rawDescGZIP(), []int{9}
}

// Deprecated: Do not use.
func (x *RequestGetCandles) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *RequestGetCandles) GetMarket() string {
	if x != nil {
		return x.Market
	}
	return ""
}

func (x *RequestGetCandles) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

// Deprecated: Do not use.
func (x *RequestGetCandles) GetTag() string {
	if x != nil {
		return x.Tag
	}
	return ""
}

func (x *RequestGetCandles) GetTsStart() int64 {
	if x != nil {
		return x.TsStart
	}
	return 0
}

func (x *RequestGetCandles) GetTsEnd() int64 {
	if x != nil {
		return x.TsEnd
	}
	return 0
}

func (x *RequestGetCandles) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *RequestGetCandles) GetBasicRequest() *BasicRequestData {
	if x != nil {
		return x.BasicRequest
	}
	return nil
}

// ReplyGetCandles - reply GetCandles
type ReplyGetCandles struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Candles *Candles `protobuf:"bytes,1,opt,name=candles,proto3" json:"candles,omitempty"`
}

func (x *ReplyGetCandles) Reset() {
	*x = ReplyGetCandles{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tradingdb2_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReplyGetCandles) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReplyGetCandles) ProtoMessage() {}

func (x *ReplyGetCandles) ProtoReflect() protoreflect.Message {
	mi := &file_tradingdb2_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReplyGetCandles.ProtoReflect.Descriptor instead.
func (*ReplyGetCandles) Descriptor() ([]byte, []int) {
	return file_tradingdb2_proto_rawDescGZIP(), []int{10}
}

func (x *ReplyGetCandles) GetCandles() *Candles {
	if x != nil {
		return x.Candles
	}
	return nil
}

// RequestUpdSymbol - request UpdSymbol
type RequestUpdSymbol struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Deprecated: Do not use.
	Token        string            `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	Symbol       *SymbolInfo       `protobuf:"bytes,2,opt,name=symbol,proto3" json:"symbol,omitempty"`
	BasicRequest *BasicRequestData `protobuf:"bytes,3,opt,name=basicRequest,proto3" json:"basicRequest,omitempty"`
}

func (x *RequestUpdSymbol) Reset() {
	*x = RequestUpdSymbol{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tradingdb2_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RequestUpdSymbol) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestUpdSymbol) ProtoMessage() {}

func (x *RequestUpdSymbol) ProtoReflect() protoreflect.Message {
	mi := &file_tradingdb2_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestUpdSymbol.ProtoReflect.Descriptor instead.
func (*RequestUpdSymbol) Descriptor() ([]byte, []int) {
	return file_tradingdb2_proto_rawDescGZIP(), []int{11}
}

// Deprecated: Do not use.
func (x *RequestUpdSymbol) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *RequestUpdSymbol) GetSymbol() *SymbolInfo {
	if x != nil {
		return x.Symbol
	}
	return nil
}

func (x *RequestUpdSymbol) GetBasicRequest() *BasicRequestData {
	if x != nil {
		return x.BasicRequest
	}
	return nil
}

// ReplyUpdSymbol - reply UpdSymbol
type ReplyUpdSymbol struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	IsOK bool `protobuf:"varint,1,opt,name=isOK,proto3" json:"isOK,omitempty"`
}

func (x *ReplyUpdSymbol) Reset() {
	*x = ReplyUpdSymbol{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tradingdb2_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReplyUpdSymbol) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReplyUpdSymbol) ProtoMessage() {}

func (x *ReplyUpdSymbol) ProtoReflect() protoreflect.Message {
	mi := &file_tradingdb2_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReplyUpdSymbol.ProtoReflect.Descriptor instead.
func (*ReplyUpdSymbol) Descriptor() ([]byte, []int) {
	return file_tradingdb2_proto_rawDescGZIP(), []int{12}
}

func (x *ReplyUpdSymbol) GetIsOK() bool {
	if x != nil {
		return x.IsOK
	}
	return false
}

// RequestGetSymbol - request GetSymbol
type RequestGetSymbol struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Deprecated: Do not use.
	Token        string            `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	Market       string            `protobuf:"bytes,2,opt,name=market,proto3" json:"market,omitempty"`
	Symbol       string            `protobuf:"bytes,3,opt,name=symbol,proto3" json:"symbol,omitempty"`
	BasicRequest *BasicRequestData `protobuf:"bytes,4,opt,name=basicRequest,proto3" json:"basicRequest,omitempty"`
}

func (x *RequestGetSymbol) Reset() {
	*x = RequestGetSymbol{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tradingdb2_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RequestGetSymbol) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestGetSymbol) ProtoMessage() {}

func (x *RequestGetSymbol) ProtoReflect() protoreflect.Message {
	mi := &file_tradingdb2_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestGetSymbol.ProtoReflect.Descriptor instead.
func (*RequestGetSymbol) Descriptor() ([]byte, []int) {
	return file_tradingdb2_proto_rawDescGZIP(), []int{13}
}

// Deprecated: Do not use.
func (x *RequestGetSymbol) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *RequestGetSymbol) GetMarket() string {
	if x != nil {
		return x.Market
	}
	return ""
}

func (x *RequestGetSymbol) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *RequestGetSymbol) GetBasicRequest() *BasicRequestData {
	if x != nil {
		return x.BasicRequest
	}
	return nil
}

// ReplyGetSymbol - reply GetSymbol
type ReplyGetSymbol struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Symbol *SymbolInfo `protobuf:"bytes,1,opt,name=symbol,proto3" json:"symbol,omitempty"`
}

func (x *ReplyGetSymbol) Reset() {
	*x = ReplyGetSymbol{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tradingdb2_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReplyGetSymbol) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReplyGetSymbol) ProtoMessage() {}

func (x *ReplyGetSymbol) ProtoReflect() protoreflect.Message {
	mi := &file_tradingdb2_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReplyGetSymbol.ProtoReflect.Descriptor instead.
func (*ReplyGetSymbol) Descriptor() ([]byte, []int) {
	return file_tradingdb2_proto_rawDescGZIP(), []int{14}
}

func (x *ReplyGetSymbol) GetSymbol() *SymbolInfo {
	if x != nil {
		return x.Symbol
	}
	return nil
}

// RequestGetSymbols - request GetSymbols
type RequestGetSymbols struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Deprecated: Do not use.
	Token        string            `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	Market       string            `protobuf:"bytes,2,opt,name=market,proto3" json:"market,omitempty"`
	Symbols      []string          `protobuf:"bytes,3,rep,name=symbols,proto3" json:"symbols,omitempty"`
	BasicRequest *BasicRequestData `protobuf:"bytes,4,opt,name=basicRequest,proto3" json:"basicRequest,omitempty"`
}

func (x *RequestGetSymbols) Reset() {
	*x = RequestGetSymbols{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tradingdb2_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RequestGetSymbols) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestGetSymbols) ProtoMessage() {}

func (x *RequestGetSymbols) ProtoReflect() protoreflect.Message {
	mi := &file_tradingdb2_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestGetSymbols.ProtoReflect.Descriptor instead.
func (*RequestGetSymbols) Descriptor() ([]byte, []int) {
	return file_tradingdb2_proto_rawDescGZIP(), []int{15}
}

// Deprecated: Do not use.
func (x *RequestGetSymbols) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *RequestGetSymbols) GetMarket() string {
	if x != nil {
		return x.Market
	}
	return ""
}

func (x *RequestGetSymbols) GetSymbols() []string {
	if x != nil {
		return x.Symbols
	}
	return nil
}

func (x *RequestGetSymbols) GetBasicRequest() *BasicRequestData {
	if x != nil {
		return x.BasicRequest
	}
	return nil
}

// RequestSimTrading - request simTrading
type RequestSimTrading struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BasicRequest *BasicRequestData `protobuf:"bytes,1,opt,name=basicRequest,proto3" json:"basicRequest,omitempty"`
	Params       *SimTradingParams `protobuf:"bytes,2,opt,name=params,proto3" json:"params,omitempty"`
}

func (x *RequestSimTrading) Reset() {
	*x = RequestSimTrading{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tradingdb2_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RequestSimTrading) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestSimTrading) ProtoMessage() {}

func (x *RequestSimTrading) ProtoReflect() protoreflect.Message {
	mi := &file_tradingdb2_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestSimTrading.ProtoReflect.Descriptor instead.
func (*RequestSimTrading) Descriptor() ([]byte, []int) {
	return file_tradingdb2_proto_rawDescGZIP(), []int{16}
}

func (x *RequestSimTrading) GetBasicRequest() *BasicRequestData {
	if x != nil {
		return x.BasicRequest
	}
	return nil
}

func (x *RequestSimTrading) GetParams() *SimTradingParams {
	if x != nil {
		return x.Params
	}
	return nil
}

// ReplySimTrading - reply simTrading
type ReplySimTrading struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Pnl []*PNLData `protobuf:"bytes,1,rep,name=pnl,proto3" json:"pnl,omitempty"`
}

func (x *ReplySimTrading) Reset() {
	*x = ReplySimTrading{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tradingdb2_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReplySimTrading) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReplySimTrading) ProtoMessage() {}

func (x *ReplySimTrading) ProtoReflect() protoreflect.Message {
	mi := &file_tradingdb2_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReplySimTrading.ProtoReflect.Descriptor instead.
func (*ReplySimTrading) Descriptor() ([]byte, []int) {
	return file_tradingdb2_proto_rawDescGZIP(), []int{17}
}

func (x *ReplySimTrading) GetPnl() []*PNLData {
	if x != nil {
		return x.Pnl
	}
	return nil
}

var File_tradingdb2_proto protoreflect.FileDescriptor

var file_tradingdb2_proto_rawDesc = []byte{
	0x0a, 0x10, 0x74, 0x72, 0x61, 0x64, 0x69, 0x6e, 0x67, 0x64, 0x62, 0x32, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x09, 0x74, 0x72, 0x61, 0x64, 0x69, 0x6e, 0x67, 0x70, 0x62, 0x1a, 0x0e, 0x74,
	0x72, 0x61, 0x64, 0x69, 0x6e, 0x67, 0x32, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xd6, 0x02,
	0x0a, 0x06, 0x43, 0x61, 0x6e, 0x64, 0x6c, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x74, 0x73, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x74, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x6f, 0x70, 0x65, 0x6e,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x6f, 0x70, 0x65, 0x6e, 0x12, 0x14, 0x0a, 0x05,
	0x63, 0x6c, 0x6f, 0x73, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x63, 0x6c, 0x6f,
	0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x68, 0x69, 0x67, 0x68, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x04, 0x68, 0x69, 0x67, 0x68, 0x12, 0x10, 0x0a, 0x03, 0x6c, 0x6f, 0x77, 0x18, 0x05, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x03, 0x6c, 0x6f, 0x77, 0x12, 0x16, 0x0a, 0x06, 0x76, 0x6f, 0x6c, 0x75,
	0x6d, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x76, 0x6f, 0x6c, 0x75, 0x6d, 0x65,
	0x12, 0x22, 0x0a, 0x0c, 0x6f, 0x70, 0x65, 0x6e, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x65, 0x73, 0x74,
	0x18, 0x07, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0c, 0x6f, 0x70, 0x65, 0x6e, 0x49, 0x6e, 0x74, 0x65,
	0x72, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x74, 0x72, 0x61, 0x64, 0x65, 0x73, 0x18, 0x08,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x74, 0x72, 0x61, 0x64, 0x65, 0x73, 0x12, 0x12, 0x0a, 0x04,
	0x76, 0x77, 0x61, 0x70, 0x18, 0x09, 0x20, 0x01, 0x28, 0x01, 0x52, 0x04, 0x76, 0x77, 0x61, 0x70,
	0x12, 0x1a, 0x0a, 0x08, 0x6c, 0x61, 0x73, 0x74, 0x53, 0x69, 0x7a, 0x65, 0x18, 0x0a, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x08, 0x6c, 0x61, 0x73, 0x74, 0x53, 0x69, 0x7a, 0x65, 0x12, 0x1a, 0x0a, 0x08,
	0x74, 0x75, 0x72, 0x6e, 0x6f, 0x76, 0x65, 0x72, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08,
	0x74, 0x75, 0x72, 0x6e, 0x6f, 0x76, 0x65, 0x72, 0x12, 0x22, 0x0a, 0x0c, 0x68, 0x6f, 0x6d, 0x65,
	0x4e, 0x6f, 0x74, 0x69, 0x6f, 0x6e, 0x61, 0x6c, 0x18, 0x0c, 0x20, 0x01, 0x28, 0x01, 0x52, 0x0c,
	0x68, 0x6f, 0x6d, 0x65, 0x4e, 0x6f, 0x74, 0x69, 0x6f, 0x6e, 0x61, 0x6c, 0x12, 0x28, 0x0a, 0x0f,
	0x66, 0x6f, 0x72, 0x65, 0x69, 0x67, 0x6e, 0x4e, 0x6f, 0x74, 0x69, 0x6f, 0x6e, 0x61, 0x6c, 0x18,
	0x0d, 0x20, 0x01, 0x28, 0x01, 0x52, 0x0f, 0x66, 0x6f, 0x72, 0x65, 0x69, 0x67, 0x6e, 0x4e, 0x6f,
	0x74, 0x69, 0x6f, 0x6e, 0x61, 0x6c, 0x22, 0x78, 0x0a, 0x07, 0x43, 0x61, 0x6e, 0x64, 0x6c, 0x65,
	0x73, 0x12, 0x16, 0x0a, 0x06, 0x6d, 0x61, 0x72, 0x6b, 0x65, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x06, 0x6d, 0x61, 0x72, 0x6b, 0x65, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x79, 0x6d,
	0x62, 0x6f, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x79, 0x6d, 0x62, 0x6f,
	0x6c, 0x12, 0x10, 0x0a, 0x03, 0x74, 0x61, 0x67, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03,
	0x74, 0x61, 0x67, 0x12, 0x2b, 0x0a, 0x07, 0x63, 0x61, 0x6e, 0x64, 0x6c, 0x65, 0x73, 0x18, 0x04,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x74, 0x72, 0x61, 0x64, 0x69, 0x6e, 0x67, 0x70, 0x62,
	0x2e, 0x43, 0x61, 0x6e, 0x64, 0x6c, 0x65, 0x52, 0x07, 0x63, 0x61, 0x6e, 0x64, 0x6c, 0x65, 0x73,
	0x22, 0x32, 0x0a, 0x08, 0x46, 0x75, 0x6e, 0x64, 0x53, 0x69, 0x7a, 0x65, 0x12, 0x12, 0x0a, 0x04,
	0x73, 0x69, 0x7a, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x02, 0x52, 0x04, 0x73, 0x69, 0x7a, 0x65,
	0x12, 0x12, 0x0a, 0x04, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04,
	0x74, 0x69, 0x6d, 0x65, 0x22, 0x8a, 0x02, 0x0a, 0x0b, 0x46, 0x75, 0x6e, 0x64, 0x4d, 0x61, 0x6e,
	0x61, 0x67, 0x65, 0x72, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x73, 0x74, 0x61, 0x72,
	0x74, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x73, 0x74, 0x61,
	0x72, 0x74, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x65, 0x6e, 0x64, 0x54, 0x69, 0x6d,
	0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x65, 0x6e, 0x64, 0x54, 0x69, 0x6d, 0x65,
	0x12, 0x1c, 0x0a, 0x09, 0x62, 0x69, 0x72, 0x74, 0x68, 0x59, 0x65, 0x61, 0x72, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x09, 0x62, 0x69, 0x72, 0x74, 0x68, 0x59, 0x65, 0x61, 0x72, 0x12, 0x10,
	0x0a, 0x03, 0x73, 0x65, 0x78, 0x18, 0x05, 0x20, 0x01, 0x28, 0x08, 0x52, 0x03, 0x73, 0x65, 0x78,
	0x12, 0x1c, 0x0a, 0x09, 0x65, 0x64, 0x75, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x06, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x09, 0x65, 0x64, 0x75, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x18,
	0x0a, 0x07, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x72, 0x79, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x07, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x73, 0x75,
	0x6d, 0x65, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6d, 0x65,
	0x12, 0x2f, 0x0a, 0x07, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x73, 0x18, 0x09, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x15, 0x2e, 0x74, 0x72, 0x61, 0x64, 0x69, 0x6e, 0x67, 0x70, 0x62, 0x2e, 0x46, 0x75,
	0x6e, 0x64, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x52, 0x07, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74,
	0x73, 0x22, 0x98, 0x02, 0x0a, 0x0a, 0x46, 0x75, 0x6e, 0x64, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74,
	0x12, 0x20, 0x0a, 0x0b, 0x6d, 0x61, 0x78, 0x44, 0x72, 0x61, 0x77, 0x64, 0x6f, 0x77, 0x6e, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x02, 0x52, 0x0b, 0x6d, 0x61, 0x78, 0x44, 0x72, 0x61, 0x77, 0x64, 0x6f,
	0x77, 0x6e, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x68, 0x61, 0x72, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x02, 0x52, 0x06, 0x73, 0x68, 0x61, 0x72, 0x70, 0x65, 0x12, 0x2c, 0x0a, 0x11, 0x61, 0x6e,
	0x6e, 0x75, 0x61, 0x6c, 0x69, 0x7a, 0x65, 0x64, 0x52, 0x65, 0x74, 0x75, 0x72, 0x6e, 0x73, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x02, 0x52, 0x11, 0x61, 0x6e, 0x6e, 0x75, 0x61, 0x6c, 0x69, 0x7a, 0x65,
	0x64, 0x52, 0x65, 0x74, 0x75, 0x72, 0x6e, 0x73, 0x12, 0x32, 0x0a, 0x14, 0x61, 0x6e, 0x6e, 0x75,
	0x61, 0x6c, 0x69, 0x7a, 0x65, 0x64, 0x56, 0x6f, 0x6c, 0x61, 0x74, 0x69, 0x6c, 0x69, 0x74, 0x79,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x02, 0x52, 0x14, 0x61, 0x6e, 0x6e, 0x75, 0x61, 0x6c, 0x69, 0x7a,
	0x65, 0x64, 0x56, 0x6f, 0x6c, 0x61, 0x74, 0x69, 0x6c, 0x69, 0x74, 0x79, 0x12, 0x22, 0x0a, 0x0c,
	0x74, 0x6f, 0x74, 0x61, 0x6c, 0x52, 0x65, 0x74, 0x75, 0x72, 0x6e, 0x73, 0x18, 0x05, 0x20, 0x01,
	0x28, 0x02, 0x52, 0x0c, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x52, 0x65, 0x74, 0x75, 0x72, 0x6e, 0x73,
	0x12, 0x1c, 0x0a, 0x09, 0x73, 0x74, 0x61, 0x72, 0x74, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x06, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x09, 0x73, 0x74, 0x61, 0x72, 0x74, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x18,
	0x0a, 0x07, 0x65, 0x6e, 0x64, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x07, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x07, 0x65, 0x6e, 0x64, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65,
	0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x8a, 0x02, 0x0a,
	0x04, 0x46, 0x75, 0x6e, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x12, 0x0a,
	0x04, 0x74, 0x61, 0x67, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x09, 0x52, 0x04, 0x74, 0x61, 0x67,
	0x73, 0x12, 0x1e, 0x0a, 0x0a, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0a, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x54, 0x69, 0x6d,
	0x65, 0x12, 0x27, 0x0a, 0x04, 0x73, 0x69, 0x7a, 0x65, 0x18, 0x05, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x13, 0x2e, 0x74, 0x72, 0x61, 0x64, 0x69, 0x6e, 0x67, 0x70, 0x62, 0x2e, 0x46, 0x75, 0x6e, 0x64,
	0x53, 0x69, 0x7a, 0x65, 0x52, 0x04, 0x73, 0x69, 0x7a, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f,
	0x6d, 0x70, 0x61, 0x6e, 0x79, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x63, 0x6f, 0x6d,
	0x70, 0x61, 0x6e, 0x79, 0x12, 0x32, 0x0a, 0x08, 0x6d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x72, 0x73,
	0x18, 0x07, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x74, 0x72, 0x61, 0x64, 0x69, 0x6e, 0x67,
	0x70, 0x62, 0x2e, 0x46, 0x75, 0x6e, 0x64, 0x4d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x72, 0x52, 0x08,
	0x6d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x72, 0x73, 0x12, 0x2f, 0x0a, 0x07, 0x72, 0x65, 0x73, 0x75,
	0x6c, 0x74, 0x73, 0x18, 0x08, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x74, 0x72, 0x61, 0x64,
	0x69, 0x6e, 0x67, 0x70, 0x62, 0x2e, 0x46, 0x75, 0x6e, 0x64, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74,
	0x52, 0x07, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x73, 0x22, 0x61, 0x0a, 0x0a, 0x53, 0x79, 0x6d,
	0x62, 0x6f, 0x6c, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x16, 0x0a, 0x06, 0x6d, 0x61, 0x72, 0x6b, 0x65,
	0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x6d, 0x61, 0x72, 0x6b, 0x65, 0x74, 0x12,
	0x16, 0x0a, 0x06, 0x73, 0x79, 0x6d, 0x62, 0x6f, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x06, 0x73, 0x79, 0x6d, 0x62, 0x6f, 0x6c, 0x12, 0x23, 0x0a, 0x04, 0x66, 0x75, 0x6e, 0x64, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x74, 0x72, 0x61, 0x64, 0x69, 0x6e, 0x67, 0x70,
	0x62, 0x2e, 0x46, 0x75, 0x6e, 0x64, 0x52, 0x04, 0x66, 0x75, 0x6e, 0x64, 0x22, 0x9c, 0x01, 0x0a,
	0x11, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x55, 0x70, 0x64, 0x43, 0x61, 0x6e, 0x64, 0x6c,
	0x65, 0x73, 0x12, 0x18, 0x0a, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x42, 0x02, 0x18, 0x01, 0x52, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x2c, 0x0a, 0x07,
	0x63, 0x61, 0x6e, 0x64, 0x6c, 0x65, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e,
	0x74, 0x72, 0x61, 0x64, 0x69, 0x6e, 0x67, 0x70, 0x62, 0x2e, 0x43, 0x61, 0x6e, 0x64, 0x6c, 0x65,
	0x73, 0x52, 0x07, 0x63, 0x61, 0x6e, 0x64, 0x6c, 0x65, 0x73, 0x12, 0x3f, 0x0a, 0x0c, 0x62, 0x61,
	0x73, 0x69, 0x63, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x1b, 0x2e, 0x74, 0x72, 0x61, 0x64, 0x69, 0x6e, 0x67, 0x70, 0x62, 0x2e, 0x42, 0x61, 0x73,
	0x69, 0x63, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x44, 0x61, 0x74, 0x61, 0x52, 0x0c, 0x62,
	0x61, 0x73, 0x69, 0x63, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x2d, 0x0a, 0x0f, 0x52,
	0x65, 0x70, 0x6c, 0x79, 0x55, 0x70, 0x64, 0x43, 0x61, 0x6e, 0x64, 0x6c, 0x65, 0x73, 0x12, 0x1a,
	0x0a, 0x08, 0x6c, 0x65, 0x6e, 0x67, 0x74, 0x68, 0x4f, 0x4b, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x08, 0x6c, 0x65, 0x6e, 0x67, 0x74, 0x68, 0x4f, 0x4b, 0x22, 0xf8, 0x01, 0x0a, 0x11, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x47, 0x65, 0x74, 0x43, 0x61, 0x6e, 0x64, 0x6c, 0x65, 0x73,
	0x12, 0x18, 0x0a, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x42,
	0x02, 0x18, 0x01, 0x52, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x16, 0x0a, 0x06, 0x6d, 0x61,
	0x72, 0x6b, 0x65, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x6d, 0x61, 0x72, 0x6b,
	0x65, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x79, 0x6d, 0x62, 0x6f, 0x6c, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x06, 0x73, 0x79, 0x6d, 0x62, 0x6f, 0x6c, 0x12, 0x14, 0x0a, 0x03, 0x74, 0x61,
	0x67, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x42, 0x02, 0x18, 0x01, 0x52, 0x03, 0x74, 0x61, 0x67,
	0x12, 0x18, 0x0a, 0x07, 0x74, 0x73, 0x53, 0x74, 0x61, 0x72, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x07, 0x74, 0x73, 0x53, 0x74, 0x61, 0x72, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x73,
	0x45, 0x6e, 0x64, 0x18, 0x06, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x74, 0x73, 0x45, 0x6e, 0x64,
	0x12, 0x12, 0x0a, 0x04, 0x74, 0x61, 0x67, 0x73, 0x18, 0x07, 0x20, 0x03, 0x28, 0x09, 0x52, 0x04,
	0x74, 0x61, 0x67, 0x73, 0x12, 0x3f, 0x0a, 0x0c, 0x62, 0x61, 0x73, 0x69, 0x63, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x18, 0x08, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x74, 0x72, 0x61,
	0x64, 0x69, 0x6e, 0x67, 0x70, 0x62, 0x2e, 0x42, 0x61, 0x73, 0x69, 0x63, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x44, 0x61, 0x74, 0x61, 0x52, 0x0c, 0x62, 0x61, 0x73, 0x69, 0x63, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x3f, 0x0a, 0x0f, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x47, 0x65,
	0x74, 0x43, 0x61, 0x6e, 0x64, 0x6c, 0x65, 0x73, 0x12, 0x2c, 0x0a, 0x07, 0x63, 0x61, 0x6e, 0x64,
	0x6c, 0x65, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x74, 0x72, 0x61, 0x64,
	0x69, 0x6e, 0x67, 0x70, 0x62, 0x2e, 0x43, 0x61, 0x6e, 0x64, 0x6c, 0x65, 0x73, 0x52, 0x07, 0x63,
	0x61, 0x6e, 0x64, 0x6c, 0x65, 0x73, 0x22, 0x9c, 0x01, 0x0a, 0x10, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x55, 0x70, 0x64, 0x53, 0x79, 0x6d, 0x62, 0x6f, 0x6c, 0x12, 0x18, 0x0a, 0x05, 0x74,
	0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x42, 0x02, 0x18, 0x01, 0x52, 0x05,
	0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x2d, 0x0a, 0x06, 0x73, 0x79, 0x6d, 0x62, 0x6f, 0x6c, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x74, 0x72, 0x61, 0x64, 0x69, 0x6e, 0x67, 0x70,
	0x62, 0x2e, 0x53, 0x79, 0x6d, 0x62, 0x6f, 0x6c, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x06, 0x73, 0x79,
	0x6d, 0x62, 0x6f, 0x6c, 0x12, 0x3f, 0x0a, 0x0c, 0x62, 0x61, 0x73, 0x69, 0x63, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x74, 0x72, 0x61,
	0x64, 0x69, 0x6e, 0x67, 0x70, 0x62, 0x2e, 0x42, 0x61, 0x73, 0x69, 0x63, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x44, 0x61, 0x74, 0x61, 0x52, 0x0c, 0x62, 0x61, 0x73, 0x69, 0x63, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x24, 0x0a, 0x0e, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x55, 0x70,
	0x64, 0x53, 0x79, 0x6d, 0x62, 0x6f, 0x6c, 0x12, 0x12, 0x0a, 0x04, 0x69, 0x73, 0x4f, 0x4b, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x04, 0x69, 0x73, 0x4f, 0x4b, 0x22, 0x9d, 0x01, 0x0a, 0x10,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x47, 0x65, 0x74, 0x53, 0x79, 0x6d, 0x62, 0x6f, 0x6c,
	0x12, 0x18, 0x0a, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x42,
	0x02, 0x18, 0x01, 0x52, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x16, 0x0a, 0x06, 0x6d, 0x61,
	0x72, 0x6b, 0x65, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x6d, 0x61, 0x72, 0x6b,
	0x65, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x79, 0x6d, 0x62, 0x6f, 0x6c, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x06, 0x73, 0x79, 0x6d, 0x62, 0x6f, 0x6c, 0x12, 0x3f, 0x0a, 0x0c, 0x62, 0x61,
	0x73, 0x69, 0x63, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x1b, 0x2e, 0x74, 0x72, 0x61, 0x64, 0x69, 0x6e, 0x67, 0x70, 0x62, 0x2e, 0x42, 0x61, 0x73,
	0x69, 0x63, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x44, 0x61, 0x74, 0x61, 0x52, 0x0c, 0x62,
	0x61, 0x73, 0x69, 0x63, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x3f, 0x0a, 0x0e, 0x52,
	0x65, 0x70, 0x6c, 0x79, 0x47, 0x65, 0x74, 0x53, 0x79, 0x6d, 0x62, 0x6f, 0x6c, 0x12, 0x2d, 0x0a,
	0x06, 0x73, 0x79, 0x6d, 0x62, 0x6f, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x15, 0x2e,
	0x74, 0x72, 0x61, 0x64, 0x69, 0x6e, 0x67, 0x70, 0x62, 0x2e, 0x53, 0x79, 0x6d, 0x62, 0x6f, 0x6c,
	0x49, 0x6e, 0x66, 0x6f, 0x52, 0x06, 0x73, 0x79, 0x6d, 0x62, 0x6f, 0x6c, 0x22, 0xa0, 0x01, 0x0a,
	0x11, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x47, 0x65, 0x74, 0x53, 0x79, 0x6d, 0x62, 0x6f,
	0x6c, 0x73, 0x12, 0x18, 0x0a, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x42, 0x02, 0x18, 0x01, 0x52, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x16, 0x0a, 0x06,
	0x6d, 0x61, 0x72, 0x6b, 0x65, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x6d, 0x61,
	0x72, 0x6b, 0x65, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x79, 0x6d, 0x62, 0x6f, 0x6c, 0x73, 0x18,
	0x03, 0x20, 0x03, 0x28, 0x09, 0x52, 0x07, 0x73, 0x79, 0x6d, 0x62, 0x6f, 0x6c, 0x73, 0x12, 0x3f,
	0x0a, 0x0c, 0x62, 0x61, 0x73, 0x69, 0x63, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x74, 0x72, 0x61, 0x64, 0x69, 0x6e, 0x67, 0x70, 0x62,
	0x2e, 0x42, 0x61, 0x73, 0x69, 0x63, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x44, 0x61, 0x74,
	0x61, 0x52, 0x0c, 0x62, 0x61, 0x73, 0x69, 0x63, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22,
	0x89, 0x01, 0x0a, 0x11, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x53, 0x69, 0x6d, 0x54, 0x72,
	0x61, 0x64, 0x69, 0x6e, 0x67, 0x12, 0x3f, 0x0a, 0x0c, 0x62, 0x61, 0x73, 0x69, 0x63, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x74, 0x72,
	0x61, 0x64, 0x69, 0x6e, 0x67, 0x70, 0x62, 0x2e, 0x42, 0x61, 0x73, 0x69, 0x63, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x44, 0x61, 0x74, 0x61, 0x52, 0x0c, 0x62, 0x61, 0x73, 0x69, 0x63, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x33, 0x0a, 0x06, 0x70, 0x61, 0x72, 0x61, 0x6d, 0x73,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x74, 0x72, 0x61, 0x64, 0x69, 0x6e, 0x67,
	0x70, 0x62, 0x2e, 0x53, 0x69, 0x6d, 0x54, 0x72, 0x61, 0x64, 0x69, 0x6e, 0x67, 0x50, 0x61, 0x72,
	0x61, 0x6d, 0x73, 0x52, 0x06, 0x70, 0x61, 0x72, 0x61, 0x6d, 0x73, 0x22, 0x37, 0x0a, 0x0f, 0x52,
	0x65, 0x70, 0x6c, 0x79, 0x53, 0x69, 0x6d, 0x54, 0x72, 0x61, 0x64, 0x69, 0x6e, 0x67, 0x12, 0x24,
	0x0a, 0x03, 0x70, 0x6e, 0x6c, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x74, 0x72,
	0x61, 0x64, 0x69, 0x6e, 0x67, 0x70, 0x62, 0x2e, 0x50, 0x4e, 0x4c, 0x44, 0x61, 0x74, 0x61, 0x52,
	0x03, 0x70, 0x6e, 0x6c, 0x32, 0xc7, 0x03, 0x0a, 0x0a, 0x54, 0x72, 0x61, 0x64, 0x69, 0x6e, 0x67,
	0x44, 0x42, 0x32, 0x12, 0x4a, 0x0a, 0x0a, 0x75, 0x70, 0x64, 0x43, 0x61, 0x6e, 0x64, 0x6c, 0x65,
	0x73, 0x12, 0x1c, 0x2e, 0x74, 0x72, 0x61, 0x64, 0x69, 0x6e, 0x67, 0x70, 0x62, 0x2e, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x55, 0x70, 0x64, 0x43, 0x61, 0x6e, 0x64, 0x6c, 0x65, 0x73, 0x1a,
	0x1a, 0x2e, 0x74, 0x72, 0x61, 0x64, 0x69, 0x6e, 0x67, 0x70, 0x62, 0x2e, 0x52, 0x65, 0x70, 0x6c,
	0x79, 0x55, 0x70, 0x64, 0x43, 0x61, 0x6e, 0x64, 0x6c, 0x65, 0x73, 0x22, 0x00, 0x28, 0x01, 0x12,
	0x4a, 0x0a, 0x0a, 0x67, 0x65, 0x74, 0x43, 0x61, 0x6e, 0x64, 0x6c, 0x65, 0x73, 0x12, 0x1c, 0x2e,
	0x74, 0x72, 0x61, 0x64, 0x69, 0x6e, 0x67, 0x70, 0x62, 0x2e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x47, 0x65, 0x74, 0x43, 0x61, 0x6e, 0x64, 0x6c, 0x65, 0x73, 0x1a, 0x1a, 0x2e, 0x74, 0x72,
	0x61, 0x64, 0x69, 0x6e, 0x67, 0x70, 0x62, 0x2e, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x47, 0x65, 0x74,
	0x43, 0x61, 0x6e, 0x64, 0x6c, 0x65, 0x73, 0x22, 0x00, 0x30, 0x01, 0x12, 0x45, 0x0a, 0x09, 0x75,
	0x70, 0x64, 0x53, 0x79, 0x6d, 0x62, 0x6f, 0x6c, 0x12, 0x1b, 0x2e, 0x74, 0x72, 0x61, 0x64, 0x69,
	0x6e, 0x67, 0x70, 0x62, 0x2e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x55, 0x70, 0x64, 0x53,
	0x79, 0x6d, 0x62, 0x6f, 0x6c, 0x1a, 0x19, 0x2e, 0x74, 0x72, 0x61, 0x64, 0x69, 0x6e, 0x67, 0x70,
	0x62, 0x2e, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x55, 0x70, 0x64, 0x53, 0x79, 0x6d, 0x62, 0x6f, 0x6c,
	0x22, 0x00, 0x12, 0x45, 0x0a, 0x09, 0x67, 0x65, 0x74, 0x53, 0x79, 0x6d, 0x62, 0x6f, 0x6c, 0x12,
	0x1b, 0x2e, 0x74, 0x72, 0x61, 0x64, 0x69, 0x6e, 0x67, 0x70, 0x62, 0x2e, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x47, 0x65, 0x74, 0x53, 0x79, 0x6d, 0x62, 0x6f, 0x6c, 0x1a, 0x19, 0x2e, 0x74,
	0x72, 0x61, 0x64, 0x69, 0x6e, 0x67, 0x70, 0x62, 0x2e, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x47, 0x65,
	0x74, 0x53, 0x79, 0x6d, 0x62, 0x6f, 0x6c, 0x22, 0x00, 0x12, 0x49, 0x0a, 0x0a, 0x67, 0x65, 0x74,
	0x53, 0x79, 0x6d, 0x62, 0x6f, 0x6c, 0x73, 0x12, 0x1c, 0x2e, 0x74, 0x72, 0x61, 0x64, 0x69, 0x6e,
	0x67, 0x70, 0x62, 0x2e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x47, 0x65, 0x74, 0x53, 0x79,
	0x6d, 0x62, 0x6f, 0x6c, 0x73, 0x1a, 0x19, 0x2e, 0x74, 0x72, 0x61, 0x64, 0x69, 0x6e, 0x67, 0x70,
	0x62, 0x2e, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x47, 0x65, 0x74, 0x53, 0x79, 0x6d, 0x62, 0x6f, 0x6c,
	0x22, 0x00, 0x30, 0x01, 0x12, 0x48, 0x0a, 0x0a, 0x73, 0x69, 0x6d, 0x54, 0x72, 0x61, 0x64, 0x69,
	0x6e, 0x67, 0x12, 0x1c, 0x2e, 0x74, 0x72, 0x61, 0x64, 0x69, 0x6e, 0x67, 0x70, 0x62, 0x2e, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x53, 0x69, 0x6d, 0x54, 0x72, 0x61, 0x64, 0x69, 0x6e, 0x67,
	0x1a, 0x1a, 0x2e, 0x74, 0x72, 0x61, 0x64, 0x69, 0x6e, 0x67, 0x70, 0x62, 0x2e, 0x52, 0x65, 0x70,
	0x6c, 0x79, 0x53, 0x69, 0x6d, 0x54, 0x72, 0x61, 0x64, 0x69, 0x6e, 0x67, 0x22, 0x00, 0x42, 0x28,
	0x5a, 0x26, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x7a, 0x68, 0x73,
	0x30, 0x30, 0x37, 0x2f, 0x74, 0x72, 0x61, 0x64, 0x69, 0x6e, 0x67, 0x64, 0x62, 0x32, 0x2f, 0x74,
	0x72, 0x61, 0x64, 0x69, 0x6e, 0x67, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_tradingdb2_proto_rawDescOnce sync.Once
	file_tradingdb2_proto_rawDescData = file_tradingdb2_proto_rawDesc
)

func file_tradingdb2_proto_rawDescGZIP() []byte {
	file_tradingdb2_proto_rawDescOnce.Do(func() {
		file_tradingdb2_proto_rawDescData = protoimpl.X.CompressGZIP(file_tradingdb2_proto_rawDescData)
	})
	return file_tradingdb2_proto_rawDescData
}

var file_tradingdb2_proto_msgTypes = make([]protoimpl.MessageInfo, 18)
var file_tradingdb2_proto_goTypes = []interface{}{
	(*Candle)(nil),            // 0: tradingpb.Candle
	(*Candles)(nil),           // 1: tradingpb.Candles
	(*FundSize)(nil),          // 2: tradingpb.FundSize
	(*FundManager)(nil),       // 3: tradingpb.FundManager
	(*FundResult)(nil),        // 4: tradingpb.FundResult
	(*Fund)(nil),              // 5: tradingpb.Fund
	(*SymbolInfo)(nil),        // 6: tradingpb.SymbolInfo
	(*RequestUpdCandles)(nil), // 7: tradingpb.RequestUpdCandles
	(*ReplyUpdCandles)(nil),   // 8: tradingpb.ReplyUpdCandles
	(*RequestGetCandles)(nil), // 9: tradingpb.RequestGetCandles
	(*ReplyGetCandles)(nil),   // 10: tradingpb.ReplyGetCandles
	(*RequestUpdSymbol)(nil),  // 11: tradingpb.RequestUpdSymbol
	(*ReplyUpdSymbol)(nil),    // 12: tradingpb.ReplyUpdSymbol
	(*RequestGetSymbol)(nil),  // 13: tradingpb.RequestGetSymbol
	(*ReplyGetSymbol)(nil),    // 14: tradingpb.ReplyGetSymbol
	(*RequestGetSymbols)(nil), // 15: tradingpb.RequestGetSymbols
	(*RequestSimTrading)(nil), // 16: tradingpb.RequestSimTrading
	(*ReplySimTrading)(nil),   // 17: tradingpb.ReplySimTrading
	(*BasicRequestData)(nil),  // 18: tradingpb.BasicRequestData
	(*SimTradingParams)(nil),  // 19: tradingpb.SimTradingParams
	(*PNLData)(nil),           // 20: tradingpb.PNLData
}
var file_tradingdb2_proto_depIdxs = []int32{
	0,  // 0: tradingpb.Candles.candles:type_name -> tradingpb.Candle
	4,  // 1: tradingpb.FundManager.results:type_name -> tradingpb.FundResult
	2,  // 2: tradingpb.Fund.size:type_name -> tradingpb.FundSize
	3,  // 3: tradingpb.Fund.managers:type_name -> tradingpb.FundManager
	4,  // 4: tradingpb.Fund.results:type_name -> tradingpb.FundResult
	5,  // 5: tradingpb.SymbolInfo.fund:type_name -> tradingpb.Fund
	1,  // 6: tradingpb.RequestUpdCandles.candles:type_name -> tradingpb.Candles
	18, // 7: tradingpb.RequestUpdCandles.basicRequest:type_name -> tradingpb.BasicRequestData
	18, // 8: tradingpb.RequestGetCandles.basicRequest:type_name -> tradingpb.BasicRequestData
	1,  // 9: tradingpb.ReplyGetCandles.candles:type_name -> tradingpb.Candles
	6,  // 10: tradingpb.RequestUpdSymbol.symbol:type_name -> tradingpb.SymbolInfo
	18, // 11: tradingpb.RequestUpdSymbol.basicRequest:type_name -> tradingpb.BasicRequestData
	18, // 12: tradingpb.RequestGetSymbol.basicRequest:type_name -> tradingpb.BasicRequestData
	6,  // 13: tradingpb.ReplyGetSymbol.symbol:type_name -> tradingpb.SymbolInfo
	18, // 14: tradingpb.RequestGetSymbols.basicRequest:type_name -> tradingpb.BasicRequestData
	18, // 15: tradingpb.RequestSimTrading.basicRequest:type_name -> tradingpb.BasicRequestData
	19, // 16: tradingpb.RequestSimTrading.params:type_name -> tradingpb.SimTradingParams
	20, // 17: tradingpb.ReplySimTrading.pnl:type_name -> tradingpb.PNLData
	7,  // 18: tradingpb.TradingDB2.updCandles:input_type -> tradingpb.RequestUpdCandles
	9,  // 19: tradingpb.TradingDB2.getCandles:input_type -> tradingpb.RequestGetCandles
	11, // 20: tradingpb.TradingDB2.updSymbol:input_type -> tradingpb.RequestUpdSymbol
	13, // 21: tradingpb.TradingDB2.getSymbol:input_type -> tradingpb.RequestGetSymbol
	15, // 22: tradingpb.TradingDB2.getSymbols:input_type -> tradingpb.RequestGetSymbols
	16, // 23: tradingpb.TradingDB2.simTrading:input_type -> tradingpb.RequestSimTrading
	8,  // 24: tradingpb.TradingDB2.updCandles:output_type -> tradingpb.ReplyUpdCandles
	10, // 25: tradingpb.TradingDB2.getCandles:output_type -> tradingpb.ReplyGetCandles
	12, // 26: tradingpb.TradingDB2.updSymbol:output_type -> tradingpb.ReplyUpdSymbol
	14, // 27: tradingpb.TradingDB2.getSymbol:output_type -> tradingpb.ReplyGetSymbol
	14, // 28: tradingpb.TradingDB2.getSymbols:output_type -> tradingpb.ReplyGetSymbol
	17, // 29: tradingpb.TradingDB2.simTrading:output_type -> tradingpb.ReplySimTrading
	24, // [24:30] is the sub-list for method output_type
	18, // [18:24] is the sub-list for method input_type
	18, // [18:18] is the sub-list for extension type_name
	18, // [18:18] is the sub-list for extension extendee
	0,  // [0:18] is the sub-list for field type_name
}

func init() { file_tradingdb2_proto_init() }
func file_tradingdb2_proto_init() {
	if File_tradingdb2_proto != nil {
		return
	}
	file_trading2_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_tradingdb2_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Candle); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tradingdb2_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Candles); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tradingdb2_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FundSize); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tradingdb2_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FundManager); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tradingdb2_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FundResult); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tradingdb2_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Fund); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tradingdb2_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SymbolInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tradingdb2_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RequestUpdCandles); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tradingdb2_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReplyUpdCandles); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tradingdb2_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RequestGetCandles); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tradingdb2_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReplyGetCandles); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tradingdb2_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RequestUpdSymbol); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tradingdb2_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReplyUpdSymbol); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tradingdb2_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RequestGetSymbol); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tradingdb2_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReplyGetSymbol); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tradingdb2_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RequestGetSymbols); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tradingdb2_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RequestSimTrading); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tradingdb2_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReplySimTrading); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_tradingdb2_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   18,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_tradingdb2_proto_goTypes,
		DependencyIndexes: file_tradingdb2_proto_depIdxs,
		MessageInfos:      file_tradingdb2_proto_msgTypes,
	}.Build()
	File_tradingdb2_proto = out.File
	file_tradingdb2_proto_rawDesc = nil
	file_tradingdb2_proto_goTypes = nil
	file_tradingdb2_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// TradingDB2Client is the client API for TradingDB2 service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type TradingDB2Client interface {
	// updCandles - update candles
	UpdCandles(ctx context.Context, opts ...grpc.CallOption) (TradingDB2_UpdCandlesClient, error)
	// getCandles - get candles
	GetCandles(ctx context.Context, in *RequestGetCandles, opts ...grpc.CallOption) (TradingDB2_GetCandlesClient, error)
	// updSymbol - update symbol
	UpdSymbol(ctx context.Context, in *RequestUpdSymbol, opts ...grpc.CallOption) (*ReplyUpdSymbol, error)
	// getSymbol - get symbol
	GetSymbol(ctx context.Context, in *RequestGetSymbol, opts ...grpc.CallOption) (*ReplyGetSymbol, error)
	// getSymbols - get symbols
	GetSymbols(ctx context.Context, in *RequestGetSymbols, opts ...grpc.CallOption) (TradingDB2_GetSymbolsClient, error)
	// simTrading - simulation trading
	SimTrading(ctx context.Context, in *RequestSimTrading, opts ...grpc.CallOption) (*ReplySimTrading, error)
}

type tradingDB2Client struct {
	cc grpc.ClientConnInterface
}

func NewTradingDB2Client(cc grpc.ClientConnInterface) TradingDB2Client {
	return &tradingDB2Client{cc}
}

func (c *tradingDB2Client) UpdCandles(ctx context.Context, opts ...grpc.CallOption) (TradingDB2_UpdCandlesClient, error) {
	stream, err := c.cc.NewStream(ctx, &_TradingDB2_serviceDesc.Streams[0], "/tradingpb.TradingDB2/updCandles", opts...)
	if err != nil {
		return nil, err
	}
	x := &tradingDB2UpdCandlesClient{stream}
	return x, nil
}

type TradingDB2_UpdCandlesClient interface {
	Send(*RequestUpdCandles) error
	CloseAndRecv() (*ReplyUpdCandles, error)
	grpc.ClientStream
}

type tradingDB2UpdCandlesClient struct {
	grpc.ClientStream
}

func (x *tradingDB2UpdCandlesClient) Send(m *RequestUpdCandles) error {
	return x.ClientStream.SendMsg(m)
}

func (x *tradingDB2UpdCandlesClient) CloseAndRecv() (*ReplyUpdCandles, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(ReplyUpdCandles)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *tradingDB2Client) GetCandles(ctx context.Context, in *RequestGetCandles, opts ...grpc.CallOption) (TradingDB2_GetCandlesClient, error) {
	stream, err := c.cc.NewStream(ctx, &_TradingDB2_serviceDesc.Streams[1], "/tradingpb.TradingDB2/getCandles", opts...)
	if err != nil {
		return nil, err
	}
	x := &tradingDB2GetCandlesClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type TradingDB2_GetCandlesClient interface {
	Recv() (*ReplyGetCandles, error)
	grpc.ClientStream
}

type tradingDB2GetCandlesClient struct {
	grpc.ClientStream
}

func (x *tradingDB2GetCandlesClient) Recv() (*ReplyGetCandles, error) {
	m := new(ReplyGetCandles)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *tradingDB2Client) UpdSymbol(ctx context.Context, in *RequestUpdSymbol, opts ...grpc.CallOption) (*ReplyUpdSymbol, error) {
	out := new(ReplyUpdSymbol)
	err := c.cc.Invoke(ctx, "/tradingpb.TradingDB2/updSymbol", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tradingDB2Client) GetSymbol(ctx context.Context, in *RequestGetSymbol, opts ...grpc.CallOption) (*ReplyGetSymbol, error) {
	out := new(ReplyGetSymbol)
	err := c.cc.Invoke(ctx, "/tradingpb.TradingDB2/getSymbol", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tradingDB2Client) GetSymbols(ctx context.Context, in *RequestGetSymbols, opts ...grpc.CallOption) (TradingDB2_GetSymbolsClient, error) {
	stream, err := c.cc.NewStream(ctx, &_TradingDB2_serviceDesc.Streams[2], "/tradingpb.TradingDB2/getSymbols", opts...)
	if err != nil {
		return nil, err
	}
	x := &tradingDB2GetSymbolsClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type TradingDB2_GetSymbolsClient interface {
	Recv() (*ReplyGetSymbol, error)
	grpc.ClientStream
}

type tradingDB2GetSymbolsClient struct {
	grpc.ClientStream
}

func (x *tradingDB2GetSymbolsClient) Recv() (*ReplyGetSymbol, error) {
	m := new(ReplyGetSymbol)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *tradingDB2Client) SimTrading(ctx context.Context, in *RequestSimTrading, opts ...grpc.CallOption) (*ReplySimTrading, error) {
	out := new(ReplySimTrading)
	err := c.cc.Invoke(ctx, "/tradingpb.TradingDB2/simTrading", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TradingDB2Server is the server API for TradingDB2 service.
type TradingDB2Server interface {
	// updCandles - update candles
	UpdCandles(TradingDB2_UpdCandlesServer) error
	// getCandles - get candles
	GetCandles(*RequestGetCandles, TradingDB2_GetCandlesServer) error
	// updSymbol - update symbol
	UpdSymbol(context.Context, *RequestUpdSymbol) (*ReplyUpdSymbol, error)
	// getSymbol - get symbol
	GetSymbol(context.Context, *RequestGetSymbol) (*ReplyGetSymbol, error)
	// getSymbols - get symbols
	GetSymbols(*RequestGetSymbols, TradingDB2_GetSymbolsServer) error
	// simTrading - simulation trading
	SimTrading(context.Context, *RequestSimTrading) (*ReplySimTrading, error)
}

// UnimplementedTradingDB2Server can be embedded to have forward compatible implementations.
type UnimplementedTradingDB2Server struct {
}

func (*UnimplementedTradingDB2Server) UpdCandles(TradingDB2_UpdCandlesServer) error {
	return status.Errorf(codes.Unimplemented, "method UpdCandles not implemented")
}
func (*UnimplementedTradingDB2Server) GetCandles(*RequestGetCandles, TradingDB2_GetCandlesServer) error {
	return status.Errorf(codes.Unimplemented, "method GetCandles not implemented")
}
func (*UnimplementedTradingDB2Server) UpdSymbol(context.Context, *RequestUpdSymbol) (*ReplyUpdSymbol, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdSymbol not implemented")
}
func (*UnimplementedTradingDB2Server) GetSymbol(context.Context, *RequestGetSymbol) (*ReplyGetSymbol, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSymbol not implemented")
}
func (*UnimplementedTradingDB2Server) GetSymbols(*RequestGetSymbols, TradingDB2_GetSymbolsServer) error {
	return status.Errorf(codes.Unimplemented, "method GetSymbols not implemented")
}
func (*UnimplementedTradingDB2Server) SimTrading(context.Context, *RequestSimTrading) (*ReplySimTrading, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SimTrading not implemented")
}

func RegisterTradingDB2Server(s *grpc.Server, srv TradingDB2Server) {
	s.RegisterService(&_TradingDB2_serviceDesc, srv)
}

func _TradingDB2_UpdCandles_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(TradingDB2Server).UpdCandles(&tradingDB2UpdCandlesServer{stream})
}

type TradingDB2_UpdCandlesServer interface {
	SendAndClose(*ReplyUpdCandles) error
	Recv() (*RequestUpdCandles, error)
	grpc.ServerStream
}

type tradingDB2UpdCandlesServer struct {
	grpc.ServerStream
}

func (x *tradingDB2UpdCandlesServer) SendAndClose(m *ReplyUpdCandles) error {
	return x.ServerStream.SendMsg(m)
}

func (x *tradingDB2UpdCandlesServer) Recv() (*RequestUpdCandles, error) {
	m := new(RequestUpdCandles)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _TradingDB2_GetCandles_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(RequestGetCandles)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(TradingDB2Server).GetCandles(m, &tradingDB2GetCandlesServer{stream})
}

type TradingDB2_GetCandlesServer interface {
	Send(*ReplyGetCandles) error
	grpc.ServerStream
}

type tradingDB2GetCandlesServer struct {
	grpc.ServerStream
}

func (x *tradingDB2GetCandlesServer) Send(m *ReplyGetCandles) error {
	return x.ServerStream.SendMsg(m)
}

func _TradingDB2_UpdSymbol_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestUpdSymbol)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TradingDB2Server).UpdSymbol(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/tradingpb.TradingDB2/UpdSymbol",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TradingDB2Server).UpdSymbol(ctx, req.(*RequestUpdSymbol))
	}
	return interceptor(ctx, in, info, handler)
}

func _TradingDB2_GetSymbol_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestGetSymbol)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TradingDB2Server).GetSymbol(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/tradingpb.TradingDB2/GetSymbol",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TradingDB2Server).GetSymbol(ctx, req.(*RequestGetSymbol))
	}
	return interceptor(ctx, in, info, handler)
}

func _TradingDB2_GetSymbols_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(RequestGetSymbols)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(TradingDB2Server).GetSymbols(m, &tradingDB2GetSymbolsServer{stream})
}

type TradingDB2_GetSymbolsServer interface {
	Send(*ReplyGetSymbol) error
	grpc.ServerStream
}

type tradingDB2GetSymbolsServer struct {
	grpc.ServerStream
}

func (x *tradingDB2GetSymbolsServer) Send(m *ReplyGetSymbol) error {
	return x.ServerStream.SendMsg(m)
}

func _TradingDB2_SimTrading_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestSimTrading)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TradingDB2Server).SimTrading(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/tradingpb.TradingDB2/SimTrading",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TradingDB2Server).SimTrading(ctx, req.(*RequestSimTrading))
	}
	return interceptor(ctx, in, info, handler)
}

var _TradingDB2_serviceDesc = grpc.ServiceDesc{
	ServiceName: "tradingpb.TradingDB2",
	HandlerType: (*TradingDB2Server)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "updSymbol",
			Handler:    _TradingDB2_UpdSymbol_Handler,
		},
		{
			MethodName: "getSymbol",
			Handler:    _TradingDB2_GetSymbol_Handler,
		},
		{
			MethodName: "simTrading",
			Handler:    _TradingDB2_SimTrading_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "updCandles",
			Handler:       _TradingDB2_UpdCandles_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "getCandles",
			Handler:       _TradingDB2_GetCandles_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "getSymbols",
			Handler:       _TradingDB2_GetSymbols_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "tradingdb2.proto",
}
